version: '3.7'
services:
  sb-app-db:
    image: arm64v8/mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '@Root123'
      MYSQL_DATABASE: sb_app
      MYSQL_USER: sb-app
      MYSQL_PASSWORD: '@Sbapp123'
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SKIP_SSL_CERT_DOWNLOAD=1
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=ANUJDEKAVADIYAEXAMPLE
      - AWS_SECRET_ACCESS_KEY=2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  sb-app-db:
